name: Docker build

on:
  push:
    branches:
    - main
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.5.3
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v4.4.0
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
      -
        name: Cache Docker layers
        uses: actions/cache@v3.2.0
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          push: true
      -
        name: Check out `wmde/wbaas-deploy` repository in staging child directory
        uses: actions/checkout@v3.5.3
        with:
          repository: wmde/wbaas-deploy
          path: ./repos/wbaas-deploy-staging
      -
        name: Check out `wmde/wbaas-deploy` repository in production child directory
        uses: actions/checkout@v3.5.3
        with:
          repository: wmde/wbaas-deploy
          path: ./repos/wbaas-deploy-production
      - 
        name: Update values for local, staging and production
        id: update-values
        run: |
          TAG="$(echo ${{ steps.docker_meta.outputs.tags }} | cut -d':' -f2)"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          sed -i "/image:/{n;s/tag:.*/tag: $TAG/;}" ./repos/wbaas-deploy-staging/k8s/helmfile/env/local/ui.values.yaml.gotmpl
          sed -i "/image:/{n;s/tag:.*/tag: $TAG/;}" ./repos/wbaas-deploy-staging/k8s/helmfile/env/staging/ui.values.yaml.gotmpl
          sed -i "/image:/{n;s/tag:.*/tag: $TAG/;}" ./repos/wbaas-deploy-production/k8s/helmfile/env/production/ui.values.yaml.gotmpl
      -
        name: Truncate commit message
        id: truncate-commit-message
        run: |
          MSG=$(echo "${{ github.event.head_commit.message }}" | head -n 1)
          echo "msg=$MSG" >> $GITHUB_OUTPUT
      -
        uses: peter-evans/create-pull-request@v4
        with:
          path: ./repos/wbaas-deploy-staging
          commit-message: 'Staging+Local: Deploy new UI image ${{ steps.docker_meta.outputs.tags }}'
          title: 'Staging+Local: Deploy new UI image ${{ steps.docker_meta.outputs.tags }}'
          branch: deploy-to-staging-${{ steps.update-values.outputs.tag }}
          committer: wmdebot <github-bots@wikimedia.de>
          author: ${{ github.actor }} <github-bots@wikimedia.de>
          labels: automated pr
          token: ${{ secrets.WBAAS_DEPLOY_TOKEN }}
          body: |
            This is an automated update for the `ui` image in staging and local, using `${{ steps.update-values.outputs.tag }}`.

            **Changes**: [${{ steps.truncate-commit-message.outputs.msg }}](https://github.com/wbstack/ui/commit/${{ github.sha }})
      -
        uses: peter-evans/create-pull-request@v4
        with:
          path: ./repos/wbaas-deploy-production
          commit-message: 'Production: Deploy new UI image ${{ steps.docker_meta.outputs.tags }}'
          title: 'Production: Deploy new UI image ${{ steps.docker_meta.outputs.tags }}'
          branch: deploy-to-production-${{ steps.update-values.outputs.tag }}
          committer: wmdebot <github-bots@wikimedia.de>
          author: ${{ github.actor }} <github-bots@wikimedia.de>
          labels: automated pr
          token: ${{ secrets.WBAAS_DEPLOY_TOKEN }}
          body: |
            This is an automated update for the `ui` image in production, using `${{ steps.update-values.outputs.tag }}`.

            **Changes**: [${{ steps.truncate-commit-message.outputs.msg }}](https://github.com/wbstack/ui/commit/${{ github.sha }})
