name: Docker lint

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v4.1.4
    - name: lint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile